
package com.webService.weather_client.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WeatherWSSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherWSSoap {


    /**
     * <br /><h3>����й�ʡ�ݡ�ֱϽ�С���������ƣ����⣩����֮��Ӧ��ID</h3><p>��������ޣ�������ݣ�DataSet��</p><br />
     * 
     * @return
     *     returns com.webService.weather_client.webxml.GetRegionDatasetResponse.GetRegionDatasetResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getRegionDataset")
    @WebResult(name = "getRegionDatasetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getRegionDataset", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetRegionDataset")
    @ResponseWrapper(localName = "getRegionDatasetResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetRegionDatasetResponse")
    public com.webService.weather_client.webxml.GetRegionDatasetResponse.GetRegionDatasetResult getRegionDataset();

    /**
     * <br /><h3>����й�ʡ�ݡ�ֱϽ�С��������֮��Ӧ��ID</h3><p>��������ޣ�������ݣ�һά�ַ����顣</p><br />
     * 
     * @return
     *     returns com.webService.weather_client.webxml.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getRegionProvince")
    @WebResult(name = "getRegionProvinceResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getRegionProvince", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetRegionProvince")
    @ResponseWrapper(localName = "getRegionProvinceResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetRegionProvinceResponse")
    public ArrayOfString getRegionProvince();

    /**
     * <br /><h3>��ù�������ƺ���֮��Ӧ��ID</h3><p>��������ޣ�������ݣ�һά�ַ����顣</p><br />
     * 
     * @return
     *     returns com.webService.weather_client.webxml.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getRegionCountry")
    @WebResult(name = "getRegionCountryResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getRegionCountry", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetRegionCountry")
    @ResponseWrapper(localName = "getRegionCountryResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetRegionCountryResponse")
    public ArrayOfString getRegionCountry();

    /**
     * <br /><h3>���֧�ֵĳ���/������ƺ���֮��Ӧ��ID</h3><p>�������theRegionCode = ʡ�С����ID����ƣ�������ݣ�DataSet��</p><br />
     * 
     * @param theRegionCode
     * @return
     *     returns com.webService.weather_client.webxml.GetSupportCityDatasetResponse.GetSupportCityDatasetResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getSupportCityDataset")
    @WebResult(name = "getSupportCityDatasetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportCityDataset", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetSupportCityDataset")
    @ResponseWrapper(localName = "getSupportCityDatasetResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetSupportCityDatasetResponse")
    public com.webService.weather_client.webxml.GetSupportCityDatasetResponse.GetSupportCityDatasetResult getSupportCityDataset(
        @WebParam(name = "theRegionCode", targetNamespace = "http://WebXml.com.cn/")
        String theRegionCode);

    /**
     * <br /><h3>���֧�ֵĳ���/������ƺ���֮��Ӧ��ID</h3><p>�������theRegionCode = ʡ�С����ID����ƣ�������ݣ�һά�ַ����顣</p><br />
     * 
     * @param theRegionCode
     * @return
     *     returns com.webService.weather_client.webxml.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getSupportCityString")
    @WebResult(name = "getSupportCityStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportCityString", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetSupportCityString")
    @ResponseWrapper(localName = "getSupportCityStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetSupportCityStringResponse")
    public ArrayOfString getSupportCityString(
        @WebParam(name = "theRegionCode", targetNamespace = "http://WebXml.com.cn/")
        String theRegionCode);

    /**
     * <br /><h3>�������Ԥ�����</h3><p>����������/����ID����ƣ�������ݣ�һά�ַ����顣</p><br />
     * 
     * @param theUserID
     * @param theCityCode
     * @return
     *     returns com.webService.weather_client.webxml.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getWeather")
    @WebResult(name = "getWeatherResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getWeather", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetWeather")
    @ResponseWrapper(localName = "getWeatherResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.webService.weather_client.webxml.GetWeatherResponse")
    public ArrayOfString getWeather(
        @WebParam(name = "theCityCode", targetNamespace = "http://WebXml.com.cn/")
        String theCityCode,
        @WebParam(name = "theUserID", targetNamespace = "http://WebXml.com.cn/")
        String theUserID);

}
