
package com.webService.weather_client.webxml;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>2400�����������Ԥ��Web����</strong>����2300�������й���к�100�����Ϲ����������Ԥ����ݡ����ÿ2.5Сʱ�����Զ�����һ�Σ�׼ȷ�ɿ���<br />ʹ�ñ�վ WEB ������ע�������ӱ�վ��<a href="http://www.webxml.com.cn/" target="_blank">http://www.webxml.com.cn/</a> ��л��ҵ�֧�֣�<br /><br /><img alt="PDF" title="PDF file" src="http://www.webxml.com.cn/images/icon/pdf.gif" style="vertical-align: middle;" /> <a href="http://www.webxml.com.cn/files/WeatherWsHelp.pdf" target="_blank">�ӿڰ����ĵ�</a> &nbsp;&nbsp;&nbsp; <img alt="ZIP" title="ZIP file" src="http://www.webxml.com.cn/images/icon/zip.gif" style="vertical-align: middle;" /> <a href="http://www.webxml.com.cn/files/about_city.zip">���ֳ��н��ܺ���򱳾�</a> &nbsp;&nbsp;&nbsp; <img alt="ZIP" title="ZIP file" src="http://www.webxml.com.cn/images/icon/zip.gif" style="vertical-align: middle;" /> <a href="http://www.webxml.com.cn/files/city_photo.zip">���ֳ���ͼƬ</a> &nbsp;&nbsp;&nbsp; <img alt="HTML" title="HTML file" src="http://www.webxml.com.cn/images/icon/html.gif" style="vertical-align: middle;" /> <a href="http://www.webxml.com.cn/zh_cn/weather_icon.aspx" target="_blank">���������ͼ��</a><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WeatherWS", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "file:/E:/eclipseWorkSpace/guoguo-maven-web/src/main/java/com/webService/weather_client/weather.wsdl")
public class WeatherWS
    extends Service
{

    private final static URL WEATHERWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.webService.weather_client.webxml.WeatherWS.class.getName());

    static {
        URL url = null; 
        try {
            URL baseUrl;
            baseUrl = com.webService.weather_client.webxml.WeatherWS.class.getResource(".");
            url = new URL(baseUrl, "file:/E:/eclipseWorkSpace/guoguo-maven-web/src/main/java/com/webService/weather_client/weather.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/eclipseWorkSpace/guoguo-maven-web/src/main/java/com/webService/weather_client/weather.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEATHERWS_WSDL_LOCATION = url;
    }

    public WeatherWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherWS() {
        super(WEATHERWS_WSDL_LOCATION, new QName("http://WebXml.com.cn/", "WeatherWS"));
    }

    /**
     * 
     * @return
     *     returns WeatherWSSoap
     */
    @WebEndpoint(name = "WeatherWSSoap")
    public WeatherWSSoap getWeatherWSSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "WeatherWSSoap"), WeatherWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherWSSoap
     */
    @WebEndpoint(name = "WeatherWSSoap")
    public WeatherWSSoap getWeatherWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "WeatherWSSoap"), WeatherWSSoap.class, features);
    }

}
